@baseURL = http://localhost:3000

### Cadastro de novo usuário
POST {{baseURL}}/users
Content-Type: application/json

{
    "name" : "victor",
    "email": "victor@ifrs",
    "password": "senhanova",
    "role": "adopter"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "victor@ifrs",
    "password": "senhanova"
}

### Consulta para buscar pets disponíveis
GET {{baseURL}}/pets/available
Content-Type: application/json
