@baseURL = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHNpc3RlbWEyLmNvbSIsInJvbGUiOiJhZG1pbiIsImlkIjo0LCJpYXQiOjE3NTEzMzc0ODgsImV4cCI6MTc1MTM0MTA4OH0.dshkXmQCEcvVVPE4HdvEej9lsDlu9X1vE34FFBDP3YA

### 📋 Listar todos os usuários
GET {{baseURL}}/users
Authorization: {{token}}

###

### 🔎 Buscar um usuário específico (substitua pelo ID real)
GET {{baseURL}}/users/2
Authorization: {{token}}

###

### ✏️ Atualizar dados do usuário (substitua o ID)
PUT {{baseURL}}/users/4
Content-Type: application/json
Authorization: {{token}}

{
  "name": "admin atualizado"
}

### ✏️ Delete dados do usuário (substitua o ID)
DELETE {{baseURL}}/users/1
Content-Type: application/json
Authorization: {{token}}


### 📋 Listar todos os pets
GET {{baseURL}}/pets
Authorization: {{token}}

###

### 🔎 Buscar um pet específico (substitua pelo ID real)
GET {{baseURL}}/pets/1
Authorization: {{token}}

###

### ✏️ criar dados do pet (substitua o ID)
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: {{token}}

{
  "name": "cachorro bonito",
  "species": "dog",
  "status": "available",
  "size": "medium",
  "description": "nao morde o dono",
  "age": 5
}

### ✏️ Atualizar dados do pet (substitua o ID)
PUT {{baseURL}}/pets/1
Content-Type: application/json
Authorization: {{token}}

{
  "name": "cachorro Atualizado"
}

### ✏️ Delete dados do pet (substitua o ID)
DELETE {{baseURL}}/pets/1
Content-Type: application/json
Authorization: {{token}}

### 🔎 Buscar todas adoptions 
GET {{baseURL}}/adoptions
Authorization: {{token}}

###

### ✏️ Realizar adoção do pet (substitua o ID)
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: {{token}}

{
  "pet_id": 2,
  "user_id": 3
}